import { type NextPage } from "next";
import Head from "next/head";
import News from "../components/News";
import Link from "next/link";
import Tables from "../components/Tables";
import type { GetServerSideProps } from "next";
import React, { useState } from "react";

const Home: NextPage = () => {

  const [players, setPlayers] = useState([
    {name: 'Marco Reus', goals: 10, assists: 10, yellow_cards: 0},
    {name: 'Robert Lewandowski', goals: 30, assists: 10, yellow_cards: 2},
    {name: 'Marcus Rashford', goals: 13, assists: 10, yellow_cards: 5},
    {name: 'Kylian Mbappe', goals: 49, assists: 30, yellow_cards: 2},
    {name: 'Bruno Fernandes', goals: 22, assists: 10, yellow_cards: 10}
  ]);

  return (
    <>
      <Head>
        <title>Kick-off EPL</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/EnglisHPremierLeague.webp" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[white] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Create <span className="text-[hsl(280,100%,70%)]">EPL</span>{" "}
            Kick-Off
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            <div
              className="flex max-w-xs flex-col gap-4 rounded-xl p-4 text-white"
              href="https://create.t3.gg/en/usage/first-steps"
              target="_blank"
            >
              {/* <h3 className="text-2xl font-bold">First Steps →</h3> */}
              <div className="flex max-w-xs flex-col gap-4 rounded-xl p-4 text-white">
  <div className="max-w-3xl" style={{ width: "700px"}}>
    <Tables players={players}/>
  </div>
</div>
            </div>
          </div>
          {/* <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://create.t3.gg/en/usage/first-steps"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">First Steps →</h3>
              <div className="text-lg">
                Just the basics - Everything you need to know to set up your
                database and authentication.
              </div>
            </Link>
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://create.t3.gg/en/introduction"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">Documentation →</h3>
              <div className="text-lg">
                Learn more about Create T3 App, the libraries it uses, and how
                to deploy it.
              </div>
            </Link>
          </div> */}
        </div>
      </main>
    </>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async () => {
  const res: Response = await fetch("http://localhost:3000/api/get/news");

  const allNews = await res.json();

  return {
    props: {
      allNews: allNews,
    },
  };
};
