import { type NextPage } from "next";
import Head from "next/head";
import News from "../components/News";
import Link from "next/link";
import Tables from '../components/Tables';
import type {GetServerSideProps} from 'next'

const Home: NextPage = ({allNews}) => {
  return (
    <>
      <Head>
        <title>Kick-off EPL</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/EnglisHPremierLeague.webp" />
      </Head>
    <News allNews={allNews}/>
    </>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async () => {

  const res: Response = await fetch('http://localhost:3000/api/get/news')


  const allNews = await res.json()

  return {props: {
    allNews : allNews}}
  }
